---
- name: Install OneAgent on HyperV Hosts
  hosts: hyperv
  roles:
    - role: dynatrace.oneagent
  vars:
    dynatrace_oneagent_host_group: 'SITE1_HYPERV'
    dynatrace_oneagent_host_properties:
      - '--set-host-property=Site=SITE1'
      - '--set-host-property=TechType=HyperV'
      - '--set-host-property=Owner=hypervteam@example.com'
      
  tasks:
    - name: Create directory structure
      ansible.windows.win_file:
        path: C:\temp
        state: directory

    - name: Creating HyperV Config File
      ansible.builtin.copy:
        src: files/hyperv/hyperv.conf
        dest: C:\temp\hyperv.conf

########################################
# Play 1: Configure SQL Hosts       #
# Task One: Install OneAgent           #
# Task Two: Create SQL config file  #
########################################
#- name: Install OneAgent on Citrix Hosts
#  hosts: sql
#  become: true
#  roles:
#    - role: dynatrace.oneagent
#  vars:
#    dynatrace_oneagent_host_group: 'SITE1_SQL'
#    dynatrace_oneagent_host_properties:
#      - '--set-host-property=Site=SITE1'
#      - '--set-host-property=TechType=SQL'
#      - '--set-host-property=Owner=sqlteam@example.com'
#
#  tasks:
#    - name: Creating SQL Config File
#      ansible.builtin.copy:
#        src: files/sql/sql.conf
#        dest: /tmp/sql.conf
